### PR TITLE
FIX - allow for long lists of users by using a gridfield #92

### LINKED ISSUE #92: Content Owners field breaks with too many members
I have a site with 10k+ members

this causes the Content Owners field to break when trying to select people to review a page. 

This field should be a gridfield (or similar) to allow people being selected as reviewers

### PR DESCRIPTION
**Pull request by torleif**
Fixes #92

### CODE REVIEW

**Comment by torleif** [comment]
@robbieaverill is there an asynchronous many-many field that comes out of the box with SilverStripe?

**Comment by robbieaverill** [comment]
I don't think so 😆 

In terms of this pull request, I think if we are going to bring this change into the main project code that it should be something that gets enabled only when a certain number of members exist in the DB (the threshold could be configurable), it'd also need to be clearly documented.

I'm still leaning towards saying that this should be implemented in project code though. How would you feel about changing this into a documentation issue so people in your position in future will know what options they have?

**Comment by robbieaverill** [comment]
TreeDropdownField might work

File: code/extensions/ContentReviewDefaultSettings.php [hunk 1]
```diff
@@ -123,8 +123,17 @@ public function updateCMSFields(FieldList $fields)
...
+					->setDescription(_t('ContentReview.OWNERUSERSDESCRIPTION', 'Page owners that are responsible for reviews'));
+
+		
+		if(Member::get()->count() > Config::inst()->get('SiteTree', 'content_review_gridfield_threshold')) {
+			$gridfieldconfig = GridFieldConfig_RelationEditor::create();
+			$gridfieldconfig->removeComponentsByType(new GridFieldAddNewButton());
+			$userField = GridField::create('OwnerUsers', _t("ContentReview.PAGEOWNERUSERS", "Users"),
+					$this->OwnerUsers()->Sort('FirstName'), $gridfieldconfig)
+					->setDescription(_t('ContentReview.OWNERUSERSDESCRIPTION', 'Page owners that are responsible for reviews'));
+		}
```
Comment (robbieaverill) [inline code/extensions/ContentReviewDefaultSettings.php]: This is starting to look better! I have two suggestions at this point:

* We should define the config prop on this extension as a `private static` and give it a PHPDoc block including `@config` annotation
* It might be a little nicer to add an `else` to this if statement which would add the `$userField` above rather than reassigning it

File: tests/SiteTreeContentReviewTest.php [hunk 2]
```diff
@@ -334,4 +334,34 @@ public function testSiteConfigSettingsAreUsedAsDefaults()
...
+        $author = $this->objFromFixture("Member", "editor");
+
+        $this->logInAs($author);
+		
+        /** @var Page|SiteTreeContentReview $page */
+        $page = $this->objFromFixture("Page", "contact");
+
+        $fields = $page->getSettingsFields();
+		
+        $this->assertTrue($fields->dataFieldByName('OwnerUsers') instanceof ListboxField);
```
Comment (robbieaverill) [inline tests/SiteTreeContentReviewTest.php]: You can use `$this->assertInstanceOf('ListboxField', $fields->da...`, same as line 365

File: code/extensions/ContentReviewDefaultSettings.php [hunk 3]
```diff
@@ -120,11 +129,19 @@ public function updateCMSFields(FieldList $fields)
...
-        $userField = ListboxField::create('OwnerUsers', _t('ContentReview.PAGEOWNERUSERS', 'Users'), $usersMap)
-            ->setMultiple(true)
-            ->setAttribute('data-placeholder', _t('ContentReview.ADDUSERS', 'Add users'))
-            ->setDescription(_t('ContentReview.OWNERUSERSDESCRIPTION', 'Page owners that are responsible for reviews'));
-
+        if(Member::get()->count() > Config::inst()->get('SiteConfig', 'content_review_gridfield_threshold')) {
+            $gridfieldconfig = GridFieldConfig_RelationEditor::create();
+            $gridfieldconfig->removeComponentsByType(new GridFieldAddNewButton());
+            $userField = GridField::create('OwnerUsers', _t("ContentReview.PAGEOWNERUSERS", "Users"),
+                    $this->OwnerUsers()->Sort('FirstName'), $gridfieldconfig)
```
Comment (robbieaverill) [inline code/extensions/ContentReviewDefaultSettings.php]: Could you remove the sorting on the OwnerUsers list here? It's not used in the SiteTreeContentReview equivalent and we should really leave it up to the default sort of the Member model

File: _config/config.yml [hunk 4]
```diff
@@ -14,5 +14,6 @@ CMSPageSettingsController:
   extensions:
     - ContentReviewCMSExtension
 SiteConfig:
+  content_review_gridfield_threshold: 2000
```
Comment (robbieaverill) [inline _config/config.yml]: I don't think we need this now that the private static is set on `ContentReviewDefaultSettings`
