### PR TITLE
FIX: Minor changes wr/t typos.

### LINKED ISSUE #59: Typo
Typo in `ContentReviewDefaultSettings`:

From:

> These content review settings will apply to all pages that does not have specific Content Review schedule.

To:

> These content review settings will apply to all pages that do not have a specific Content Review schedule.

### PR DESCRIPTION
**Pull request by phptek**
FIX: Fixes #59 Minor changes wr/t typos.

### CODE REVIEW

File: code/extensions/ContentReviewDefaultSettings.php [hunk 1]
```diff
@@ -94,7 +94,7 @@ public function updateCMSFields(FieldList $fields)
             'ContentReviewHelp',
             _t(
                 'ContentReview.DEFAULTSETTINGSHELP',
-                'These content review settings will apply to all pages that does not have specific Content Review schedule.'
+                'These settings will apply to all pages that do not have a specific Content Review schedule.'
```
Comment (robbieaverill) [inline code/extensions/ContentReviewDefaultSettings.php]: Would you mind please updating these in `lang/en.yml` as well?

**Comment by phptek** [comment]
Oops. Done.

**Comment by robbieaverill** [comment]
Build failure is unrelated
